#google_analytics: UA-NNNNNNNN-N

site-title: Musings by Pratik Nilange

header_pages:
 - index.md
 - about.md

footer: 🌊

style: light # dark (default) or light
#listen_for_clients_preferred_style: true # true or false (default)

permalink: pretty

plugins:
  - jekyll-seo-tag