#google_analytics: UA-NNNNNNNN-N

site-title: Musings by Pratik Nilange

header_pages:
 - index.md
 - about.md

footer: don't follow me on <a href="https://x.com/nilnge">twitter</a>

style: light # dark (default) or light
#listen_for_clients_preferred_style: true # true or false (default)

plugins:
  - jekyll-seo-tag